### ISSUE TITLE
Site content taxonomy

### ISSUE THREAD

**Issue by caseyyee** [WebVRRocks/webvrrocks#121]
As discussed with @cvan, 
sites content taxonomy looks like:

`/news/[year]/[month]/[article-name]` for news
`/article/[article-name]` for articles

**Comment by cvan** [comment]
This could feel inconsistent, but I understand why. Also I would make `article` plural: `articles`.

The articles we expect to keep up to date always when possible, yeah? I don't want to be too prescriptive but perhaps `/wiki/` is a better name.

**Comment by cvan** [comment]
We're making all pages flat now: `/firefox`, `/oculus_rift`, `/deploying_to_neocities`, etc.
