### ISSUE TITLE
Choose a good poster image to "What is WebVR?" video

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#157]
The poster image (the thumbnail/cover image) may have been intentionally chosen (it's not bad; it just could be more representative of WebVR and/or the WebVR Rocks branding/logo).

See on the [WebVR Rocks site](http://localhost:3000/):
<img width="582" alt="screen shot 2017-01-26 at 1 14 47 am" src="https://cloud.githubusercontent.com/assets/203725/22325869/1d602338-e365-11e6-8435-6188a8b76cd7.png">

See on the [WebVR Rocks YouTube channel page](https://www.youtube.com/channel/UC1QNxz8OJLJ6DuudjeYK-dw) (["What is WebVR?" video](https://www.youtube.com/watch?v=XyNNCuUXrso)):
![image](https://cloud.githubusercontent.com/assets/203725/22325813/d890f69c-e364-11e6-998e-d6a3dc080b3e.png)

**Comment by caseyyee** [comment]
Doesn't look like I can change poster image until account is verified.

**Comment by cvan** [comment]
this is done now
