### ISSUE TITLE
Make nav responsive on mobile

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#16]
Ideally, we show only the important content. Perhaps even a `<select>` with the nav items on might work fine on mobile (iOS and Android, at least, style `<select>` drop-down menus very nicely).

I hate using hamburger menus for primary navigation, but if someone must, try using [this third-party vanilla JS+CSS component](https://frend.co/components/dialogmodal/).

**Comment by cvan** [comment]
@caseyyee pointed out how [Surge.sh's mobile nav works](https://surge.sh/help/getting-started-with-surge). Like it: clicking "Menu" scrolls down to footer nav for "site nav" links and the "Table of Contents" button exposes a list for "page nav" links. 👍 to that approach.

**Comment by caseyyee** [comment]
https://github.com/WebVRRocks/webvrrocks/commit/f6a697edbc7a7348996de7134f060ab2674d46b1
