### ISSUE TITLE
Merge two "VR headsets" landing pages

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#17]
* https://webvrrocks.surge.sh/headsets/
* https://webvrrocks.surge.sh/getting-started/headsets/

**Comment by cvan** [comment]
And ensure the links to those pages are all updated consistently.

**Comment by caseyyee** [comment]
fixed with https://github.com/WebVRRocks/webvrrocks/commit/e1360a3c9aaefd7838452790df26047be2e7c165
