### ISSUE TITLE
Decide on (and document) Slack chat room name

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#29]
* [https://webvr.slack.com/messages/webvr-rocks](#webvr-rocks)
* [https://webvr.slack.com/messages/webvrrocks](#webvrrocks)
* [https://webvr.slack.com/messages/rocks](#rocks)

Thoughts?

**Comment by caseyyee** [comment]
what's /messages?

Sounds good to me.

Also related https://github.com/WebVRRocks/webvrrocks/issues/44

**Comment by cvan** [comment]
Messages is just part of the URL for a room

**Comment by cvan** [comment]
Done, it's `#rocks`
