### ISSUE TITLE
Use an open-source typeface for wordmark in the logo

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#32]
I'm using Akzidenz-Grotesk, but IMO we should use an open-source font for an open Web standard. I'm liking these so far:

* [Nimbus Sans L Bold](http://open-foundry.com/hot30/nimbus_sans_l_bold)
* [Roboto Black Italic](http://open-foundry.com/hot30/roboto_black_italic)
* [Tex Gyre Heros Bold Italic](http://open-foundry.com/hot30/tex_gyre_heros_bold_italic)
* [Liberation Sans Bold](http://open-foundry.com/hot30/liberation_sans_bold)

**Comment by cvan** [comment]
Another one from @321C4: https://fonts.google.com/specimen/Francois+One

**Comment by 321C4** [comment]
Can't go wrong with Roboto -- looks great and is super legible!

**Comment by cvan** [comment]
We're going to use the [San Francisco fonts](https://developer.apple.com/fonts/).
