### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#34]

**Comment by cvan** [comment]
We can adapt [Rust's popular Code of Conduct](https://www.rust-lang.org/en-US/conduct.html).

**Comment by caseyyee** [comment]
https://github.com/WebVRRocks/webvrrocks/commit/7e9204f21077aeae87d0f530efed79c5602cbf8a

Adapted from Rust-lang.

Also see: https://github.com/WebVRRocks/webvrrocks/issues/39
