### ISSUE TITLE
Guide: Create a simple A-Frame scene from Blender models found on Sketchfab

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#50]
Write a 5-minute guide of how to find a Blender model from [Sketchfab](https://sketchfab.com/] and export to a basic [A-Frame](https://aframe.io/) scene outlining these steps:

1. Find a "downloadable" model on Sketchfab that comes in a Blender format (e.g., this [Oculus Rift CV1](https://sketchfab.com/models/591ff55a0f7b401cbb14fe454175b8b2) seems like a good start). (Link to where find [other Blender models](https://sketchfab.com/tags/blender) and [free, downloadable models on SketchFab](https://sketchfab.com/search?features=downloadable&q=&type=models)).
2. Show a video (you can use QuickTime Player on macOS to record) of how to unzip/extract the `.zip` files (on Windows and/or macOS).
3. Show how to download and install [Blender](https://www.blender.org).
4. Launch Blender and import the raw Blender file.
5. Export the Blender file to an appropriate format (likely OBJ/MTL or COLLADA).
6. Show how to drop the create a scene locally w/ a simple local dev server (using [Prepos](https://prepros.io/), [Mongoose](https://www.cesanta.com/products/binary), `python -m HTTPServer`/`python3 -m http.server`, [jus](http://jus.js.org), [`http-server`](https://www.npmjs.com/package/http-server), etc.).
7. _(Optional):_ Show how to deploy to a simple web host such as **[Neocities](https://neocities.org)**.

<hr>

**Inspiration:**
* **https://github.com/ngokevin/aframe-blender-projects**
* **https://medium.com/@bnolan/using-thingiverse-files-in-a-frame-50641ca3f721#.9gxpb0xjo**
* https://surge.sh/help/getting-started-with-surge

**Related issues:**
* #49 - Guide: Exporting Thingiverse Models to A-Frame

**Comment by cvan** [comment]
Source: https://sketchfab.com/search?features=downloadable&q=&type=models

**Comment by 321C4** [comment]
@cvan People making VR stuff will be using Windows.. perhaps I could record on Windows using some recorder like Jing. 

Also, in B Nolan's Thingiverse to A-Frame article, he uses a ton of keyboard/text shortcuts to avoid having to deal with the Blender UI. That way, it's easier to explain quickly, but it's like using Blender as if it were a cmd line tool, rather than a graphical tool.

**Comment by 321C4** [comment]
Looking for an alternative to that CV1 model on Sketchfab.... It looks great as Collada, but some issues with flipped normals in .obj format. Since the model is in several pieces, fixing the normals is a fiddly process. Looking for a model with only one mesh, for the sake of the tutorial.

**Comment by 321C4** [comment]
Searching for a simpler (less polygons) Blender model on Sketchfab. There are so few things that are free to download.. I've tested a few different models, all with awful results: mostly issues with shaders and textures. Thinking it may be worth it to go back and use that Rift model, and provide some tips for troubleshooting. 

(Looking forward to making and thoroughly testing a bunch of free assets for people to use!!! Providing in Blender format would give people the freedom to edit, and also export in whatever format they want.)

**Comment by 321C4** [comment]
Two glitches encountered with .obj, that may trouble people attempting this same process: 
![screenshot 52](https://cloud.githubusercontent.com/assets/8229343/20200923/2235fabe-a769-11e6-925a-33f748581786.png)

**Comment by cvan** [comment]
fixed by #77. will open follow-up issues to handle bugs and any gaps.
