### ISSUE TITLE
sw.js errors

### ISSUE THREAD

**Issue by caseyyee** [WebVRRocks/webvrrocks#71]
sw.js:1 A bad HTTP response code (404) was received when fetching the script.
http://localhost:3000/sw.js Failed to load resource: net::ERR_INVALID_RESPONSE

![image](https://cloud.githubusercontent.com/assets/1560884/20232977/f6802f80-a820-11e6-8edd-b6e1f522ea7d.png)

**Comment by cvan** [comment]
This ought to be fixed for you, yeah?
