### ISSUE TITLE
Choose a legible, neat font for body text

### ISSUE THREAD

**Issue by cvan** [WebVRRocks/webvrrocks#97]
In the [Sketch design files](https://github.com/WebVRRocks/branding/tree/master/Sketch-1) for @hudsonpowell + @benjaminleonard's refresh of @caseyyee's _designsgit,_ [Poppins](https://fonts.google.com/specimen/Poppins) is used as the typeface for the headings and copy.

Poppins looks good for headline type treatments (e.g., for the wordmark and headings), but for copy Poppins' legibility leaves a little to be desired:

![image](https://cloud.githubusercontent.com/assets/203725/20755200/f6d343cc-b6c2-11e6-8e77-c686dc89961a.png)

For body text, I'd recommend we use the default **["system" font](https://jonathantneal.github.io/system-font-css/)** ([project repo](https://github.com/jonathantneal/system-font-css)).

Alternatively, IMO, the `Helvetica Neue, Helvetica, Arial, sans-serif` family could work quite well.

Another typeface I really like and think works well for body text is Apple's **["San Francisco" font](https://developer.apple.com/fonts/)** (`SFUIText` and `SFUIDisplay`). Here's a good treatment of it on the [SCRN App site](http://newscrnapp.com.s3-website-us-west-2.amazonaws.com/):

![image](https://cloud.githubusercontent.com/assets/203725/20754866/b6518bac-b6c1-11e6-99ac-d89c5754dd17.png)

(By the way, I've introduced the open-source monospace font ["Hack"](http://sourcefoundry.org/hack/) for when we display code.)

**Comment by HudsonPowell** [comment]
@cvan sounds good. let's go with system sans and have a rethink if it's looking like an odd paring with with poppins
